- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: Course
      prompt: "Enter the course name"
      private: no
    - name: Duration
      prompt: "Enter the course duration"
      private: no
    - name: Trainer
      prompt: "Enter the trainer name"
      private: no
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello, iam learing the  {{ Course  }}, the course duration: {{ Duration }}, Trainer is {{ Trainer }}"