- name: conditons Demo
  hosts: localhost
  connection: local
  vars:
    number: 50
  tasks: 
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "The number is less than or equal to 100"
    when: number <= 100
   