- name: conditons Demo
  hosts: localhost
  connection: local
  vars:
    number: 510
  tasks: 
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "The number is less than  equal to 100"
    when: number <= 100
   
  - name: print if the number is Greater than or equal to 100
    ansible.builtin.debug:
        msg: "The number is greater than or equal to 100"
    when: number >= 100